### PR TITLE
NY: Add new event type when parsing listings

### PR DESCRIPTION
**Pull request by mileswwatkins**

### CODE REVIEW

**Comment by rshorey** [comment]
@mileswwatkins runs fine locally, is there a specific event I should check to make sure I'm getting the right data?

**Comment by rshorey** [comment]
Also it looks like Summit is misspelled. Is that our mistake or matching theirs? If it's theirs, could you comment that?

**Comment by mileswwatkins** [comment]
@rshorey, the scraper should be failing on [this page](http://assembly.state.ny.us/leg/?sh=hear), since it doesn't look for "Public Forum"s.

**Comment by rshorey** [comment]
OK, looks good on both fronts now, I'll merge.

**Pull request merged**
