### PR TITLE
CA: Add 2015 special session

### PR DESCRIPTION
**Pull request by mileswwatkins**
Don't pull this in yet! @rshorey is going to run it locally on her machine; I'm not sure that the `download.py` and then `billy-update ca --bills` are working properly for the new session.

### CODE REVIEW

**Comment by rshorey** [comment]
there are no bills in the 2016 session. should we ignore it for now? put it in but run with --session=2015?

**Comment by mileswwatkins** [comment]
Hmm, yeah. I'm confused about this in general, since if you run with `--session "20132014 Special Session 1"` you also get the "no bills returned" error, even though that appears to be a legitimate `session` in the `__init__.py` and has 10 bills in the production database. @paultag, what am I missing?

**Comment by paultag** [comment]
Hurm. Cache?

**Comment by mileswwatkins** [comment]
Cali's the one where all the bills come from the MySQL database dump, so maybe it just contains bills for the current session.

**Comment by mileswwatkins** [comment]
@rshorey, I keep having timeout issues updating the California DB on my machine. Could you take this PR over from here? Should be pretty basic; can't believe it's been this much of a pain with my MySQL setup =/

**Comment by mileswwatkins** [comment]
There _are_ extraordinary session bills; they just have weird names (like `SBX1 4` for "Senate Bill 4 from Extraordinary Session 1"). Not sure if this clarifies anything. Eg:
- http://www.legislature.ca.gov/cgi-bin/port-postquery?bill_number=sbx1_2&sess=CUR&house=B&author=huff_%3Chuff%3E
- http://www.legislature.ca.gov/cgi-bin/port-postquery?bill_number=sbx2_5&sess=CUR&house=B&author=leno_%3Cleno%3E
- http://www.legislature.ca.gov/cgi-bin/port-postquery?bill_number=abx1_2&sess=CUR&house=B&author=perea_%3Cperea%3E

**Comment by rshorey** [comment]
replaced by #795

**Pull request closed without merging**
