### PR TITLE
FL: Added new session, which is currently in progress

### PR DESCRIPTION
**Pull request by mileswwatkins**
Also clean up titles from sponsor names.

### CODE REVIEW

**Comment by rshorey** [comment]
When I run this locally I get:

AssertionError: Bill search pagination needed but not used

**Comment by mileswwatkins** [comment]
I added that `warning` just now. Basically, I want it to highlight the fact that the pagination isn't being used in the bill search. (Specifically, that the "next" button isn't found.) It's innocuous right now because there _are_ genuinely few bills, but I think it's more of a `warning` than a `debug`. Good way to keep the code fragile.

**Comment by mileswwatkins** [comment]
Oh, er, uh, I'll look into that. Misread :)

**Comment by rshorey** [comment]
Indeed when I downloaded the newer version of libxml2 it worked.

**Comment by rshorey** [comment]
OK, now that I've got it working...we're not scraping any bills from the house. Looks like they're not even acknowledging the special session yet. Is that of any concern?

**Comment by mileswwatkins** [comment]
Both the House and the Senate are in on it, but AFAICT only the Senate has bills filed in it so far.

**Comment by rshorey** [comment]
OK, all looks good.

**Pull request merged**
