### PR TITLE
New Mexico leg/bills ready to go

### PR DESCRIPTION
**Pull request by rshorey**
there haven't been any votes yet besides this, which doesn't seem to match to any bill:

http://www.nmlegis.gov/Sessions/15%20Regular/votes/T3SN6.PDF

otherwise this is running and seems to be working correctly

### CODE REVIEW

**Comment by paultag** [comment]
can we run `.strip()` on names? I see trailing spaces in names

**Comment by rshorey** [comment]
added .strip() to names, also moved email from the top level to the office (happened to notice that while I was in there)

**Comment by paultag** [comment]
:+1: - i'll take a look at the merge now

**Comment by paultag** [comment]
Hurm; can we also get rid of `Senator` and `Representative` from the `full_name` field?

**Comment by rshorey** [comment]
sen/rep removed from full_name

**Comment by paultag** [comment]
:+1: awesome, thanks!

**Pull request merged**
