### PR TITLE
Updated Louisiana legislators.py

### PR DESCRIPTION
**Pull request by iCandyLabs**
Please review this code and test.

### CODE REVIEW

**Comment by paultag** [comment]
seems like there's a bunch of trailing commas 

I'll see if I can get to patching some of this up before EOD

Thanks!

**Comment by iCandyLabs** [comment]
Does this error fall outside of the work I have done?  Or have I done inferior work for update?

**Comment by paultag** [comment]
@iCandyLabs I wouldn't say inferior -- it's just something you might not know to look for -- stuff like:

`"full_name": "David R. Heitmeier,"`

**Comment by paultag** [comment]
It's no worries, you did a bunch of work, we can handle landing it :)

:+1: thanks!

**Comment by iCandyLabs** [comment]
Thanks @paultag :)  I appreciate the support.  I want to help and I'm glad I can contribute!

**Comment by iCandyLabs** [comment]
I will try to remove those trailing commas from the "full_name" item.  Were you able to dig in yesterday?

**Comment by paultag** [comment]
Only briefly - today is a meeting day, I think Miles is digging in today

**Comment by mileswwatkins** [comment]
I'm currently working on some additional LA edits; please wait until I push these before editing `legislators.py` further.

**Pull request closed without merging**
