### PR TITLE
AL: leg rewritten

### PR DESCRIPTION
**Pull request by rshorey**
data should probably be double checked. this one was ugly.

also I'm stuck on e-mail addresses for reps.

### CODE REVIEW

**Comment by mileswwatkins** [comment]
@paultag: we can't remember; do we title() committee names, or lower() them?

**Comment by paultag** [comment]
We should maintain casing as exists on the state site

**Comment by mileswwatkins** [comment]
Gosh darn, @rshorey, I just can't figure out how representative pages are generated. I think that they're coming from a POST request to the main representative page with the headers:
```__EVENTTARGET:ctl00$HseMainContent$tabByName$TabPanel1$gvINFO```
```__EVENTARGUMENT:cmdRep$5``` (change that last number for the representative's alphabetical order in the current term)

If this sparks something for you on Tuesday then make that edit, but I'm guessing you already thought of that. Otherwise, removing the committee name lower() on line 215 is the only edit I see that needs to be made before pulling this branch in.

**Comment by paultag** [comment]
Guys, it's OK to have a weekend :)

**Comment by mileswwatkins** [comment]
MAKE ME

**Comment by paultag** [comment]
:heart:

**Pull request merged**
