### PR TITLE
LA: event scraper now run-able

### PR DESCRIPTION
**Pull request by rshorey**
If we want to run, we should turn off everything else. This was just a super easy fix - no actual formatting changes, just a few bad dates - so seemed worth it!

### CODE REVIEW

**Comment by paultag** [comment]
:+1: thanks!

**Comment by paultag** [comment]
@icandylabs - we just landed this and flipped on events. More to come in the #631 update.

**Comment by iCandyLabs** [comment]
Awesome!  Do you plan to turn on the events & bill scraping?  I am working on committees.py as we speak and should have it working properly by EOD.  Next, I will start fixing legislators.py

**Comment by paultag** [comment]
Events should be running starting today unless there are more bugs.

Bills are waiting on that other PR.

On Wed, Mar 18, 2015 at 2:17 PM, iCandyLabs <notifications@github.com>
wrote:

> Awesome! Do you plan to turn on the events & bill scraping? I am working
> on committees.py as we speak and should have it working properly by EOD.
> Next, I will start fixing legislators.py
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sunlightlabs/openstates/pull/631#issuecomment-83107433>
> .
>



-- 
Paul Tagliamonte
Software Developer | Sunlight Foundation

**Pull request merged**
