### PR TITLE
fixed legislators / committees scrapers

### PR DESCRIPTION
**Pull request by iCandyLabs**
I have fixed the committee and legislators scrapers

### CODE REVIEW

**Comment by iCandyLabs** [comment]
I see that my committee scraper seems to work but the mongo db for committees has a null value for leg_id key. Any suggestions about how to fix that?

**Comment by paultag** [comment]
Just merged this! GitHub is acting flaky, closing!

**Comment by iCandyLabs** [comment]
Did you test this code?  Will this run tonight?

**Comment by paultag** [comment]
I did test it, and it should have run, let me check

**Comment by iCandyLabs** [comment]
I am not seeing the 2015 bills from last night's scrape.

**Comment by iCandyLabs** [comment]
now they are live :)

**Pull request closed without merging**
