### PR TITLE
OH: Fix bill source URLs

### PR DESCRIPTION
**Pull request by mileswwatkins**

### CODE REVIEW

**Comment by mileswwatkins** [comment]
The Ohio API's endpoint is `/bills/`, not `/bill/`.

**Comment by rshorey** [comment]
How about resolutions? Does this also hold? If so, maybe we should just clean up the code that removes the 's' directly above the line you changed.

**Comment by mileswwatkins** [comment]
It _does_ hold for resolutions as well. Does this code strike your fancy?

**Comment by rshorey** [comment]
yes!

**Pull request merged**
