### PR TITLE
DC: fix actors on committees

### PR DESCRIPTION
**Pull request by rshorey**

### CODE REVIEW

**Comment by paultag** [comment]
:+1: thank you!

**Comment by mileswwatkins** [comment]
This is coming up with some weird actors for me. When I `grep` for "legislator" inside the `bills` JSON, most of the legislator names I get are "the Mayor" (wouldn't that be "executive" instead?). I also get one "legislator" named "the University of the District of Columbia" (for bill `21_upper_CA21-0010`).

**Comment by paultag** [comment]
@mileswwatkins was that present before this changeset too? We might need to do another PR

**Comment by mileswwatkins** [comment]
I'm not sure, but there's a good chance that's the case.

**Comment by mileswwatkins** [comment]
I'll file a Jira bug.

**Comment by paultag** [comment]
:heart: - let's get another chanceset addressing issues

**Pull request merged**
