### PR TITLE
Updated to show business phone if there isn't a home phone available.

### PR DESCRIPTION
**Pull request by linzjax**

### CODE REVIEW

**Comment by rshorey** [comment]
Change looks good! @linzjax, could you get rid of that extra print statement in line 69 while you're in there, though (you didn't add it, but might as well clean it up)? When you've done it, just make a commit to the same branch and push it, and then make a comment here so I know you've made the change, and I'll pull it in!

**Comment by mileswwatkins** [comment]
Could you clean out some of the excess whitespace? Also, it looks like there was an existing `print` in the scraper; could you remove that?

Otherwise, works great for me!

**Comment by rshorey** [comment]
man, team openstates on the same page today :)

**Comment by mileswwatkins** [comment]
:trophy:

**Comment by linzjax** [comment]
@rshorey Done! Today I learned about linters and branches. It was a good day.

**Comment by rshorey** [comment]
Great! thanks.

**Pull request merged**
