### PR TITLE
DE: legislators no longer fails

### PR DESCRIPTION
**Pull request by rshorey**
now skips empty/blank legislators

### CODE REVIEW

**Comment by paultag** [comment]
Hurm, where was this coming from? Vacancies or HTML structural quirks?

This makes me a bit scared we'll drop all people if an xpath breaks (although I guess we'll just get a scrape failure for no people)

**Comment by rshorey** [comment]
Seems like a html quirk. they accidentally put an extra row with only the value " ." in their table. I can make a more specific test for exactly that string?

**Comment by rshorey** [comment]
fixed more narrowly.

**Comment by paultag** [comment]
:+1: thanks!

**Pull request merged**
