### PR TITLE
MD: committee spacing issue fixed

### PR DESCRIPTION
**Pull request by rshorey**
Also included committees labelled as "other" as joint committees bc most seem to have members from both parties.

Also also, this will cause us to create a bunch of duplicate committees that will presumably have to be removed.

### CODE REVIEW

**Comment by mroswell** [comment]
Did you mean "joint committees bc most seem to have members from both **chambers**."

(I'm also curious: why would that create duplicates?)

Also what happens with the "Senate Special" and "House Special" committees at 
http://mgaleg.maryland.gov/webmga/frmcommittees.aspx?pid=commpage&tab=subject7

**Comment by paultag** [comment]
@mroswell yeah, I assume @rshorey means chamber not party.

It would create duplicates since we don't delete committees if we don't scrape them, but they'll be empty. That's only a major concern if it's Legislators, since it will cause issues during name resolution, causing mass unlinking of related entities. We merge in that case, but we remove empty committees.

**Comment by paultag** [comment]
Looks good, thanks @rshorey!

**Comment by rshorey** [comment]
Special House/Senate Special committees will be attached to the relevant chamber, since we're checking for the word "House" or "Senate" in the header of each committee. There's a warning if the scraper fails to find a chamber, so we should get a heads up if any committees don't get assigned to a chamber.

**Comment by mroswell** [comment]
I'm not seeing the special committees at
http://openstates.org/api/v1/committees/?state=md&apikey=APIKEY

Equivalent on my developing site:
http://legislativecommittees.org/?state=md

(Aside: I just alerted the webmaster for 
http://mgaleg.maryland.gov/webmga/frmcommittees.aspx?pid=commpage&tab=subject7 
of a typo in spelling "committee" in the Senate Special committee listing.)

**Pull request merged**
