### PR TITLE
Remove all calls to scrapelib.urlopen()

### PR DESCRIPTION
**Pull request by mileswwatkins**
[So many instances](http://cdn.meme.am/instances/500x/60705889.jpg).

All that should remain will be fixed in the other existing pull requests.

### CODE REVIEW

**Comment by rshorey** [comment]
Error in RI bills: 

Traceback (most recent call last):
  File "/home/rachel/.virtualenvs/openstates/bin/billy-update", line 9, in <module>
    load_entry_point('billy==1.8.0', 'console_scripts', 'billy-update')()
  File "/home/rachel/.virtualenvs/openstates/local/lib/python2.7/site-packages/billy/bin/update.py", line 392, in main
    run_record += _run_scraper(stype, args, metadata)
  File "/home/rachel/.virtualenvs/openstates/local/lib/python2.7/site-packages/billy/bin/update.py", line 101, in _run_scraper
    scraper.scrape(chamber, time)
  File "/home/rachel/work/openstates/openstates/ri/bills.py", line 291, in scrape
    subjects = self.get_subject_bill_dict(session)
  File "/home/rachel/work/openstates/openstates/ri/bills.py", line 159, in get_subject_bill_dict
    data=default_headers))
  File "/home/rachel/work/openstates/openstates/ri/bills.py", line 86, in parse_results_page
    p = lxml.html.fromstring(page)
  File "/home/rachel/.virtualenvs/openstates/local/lib/python2.7/site-packages/lxml/html/__init__.py", line 722, in fromstring
    is_full_html = _looks_like_full_html_unicode(html)
TypeError: expected string or buffer

**Comment by mileswwatkins** [comment]
Thanks muchly, got that!

**Comment by rshorey** [comment]
Everything else I've run looks good!

**Comment by rshorey** [comment]
just reran ri bills and looks good. @mileswwatkins can you confirm you're not working on anything else and I'll merge?

**Pull request merged**
