### PR TITLE
IN: fixed packet error crashing, maybe?

### PR DESCRIPTION
**Pull request by rshorey**
I have never reproduced this error locally, but this ought to work?

### CODE REVIEW

**Comment by paultag** [comment]
Hurm. I think a SyscallError might capture too much. Was that the thing raised (if it was, we might just have to deal with it :) )

**Comment by rshorey** [comment]
File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 862, in _raise_ssl_error
    raise SysCallError(errno, errorcode[errno])
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')

Is there a way to specify the arguments in a python exception? Otherwise SysCallError is what we've got.

is

**Comment by paultag** [comment]
Yeah, try:

```python
try:
    .....
except Thing as e:
    err, string = e.args
    if err != 104:
        raise
    # (error handling here)
```

**Comment by paultag** [comment]
I just checked in the SSL code, it's a plain subclass, looks like that should work.

**Comment by rshorey** [comment]
ok @paultag I think this should take care of it.

**Comment by paultag** [comment]
:+1: thank you!

**Pull request merged**
