### PR TITLE
IN: bill version order reversed

### PR DESCRIPTION
**Pull request by rshorey**

### CODE REVIEW

**Comment by mileswwatkins** [comment]
Could you give an example of a current-session `bill` with multiple `version`s?

**Comment by rshorey** [comment]
http://openstates.org/in/bills/2015/SB101/

**Comment by mileswwatkins** [comment]
Otherwise, the code update looks great! Merge it in once you make that one tweak.

**Comment by rshorey** [comment]
so it looks like we've been really inconsistent about this - I grep'd for it, and we've used both as actor relatively frequently. Could not find documentation on one vs the other. @paultag, is "governor" or "executive" preferred for actor when a bill is signed?

**Comment by rshorey** [comment]
confirmed with @paultag that "executive" is preferred here.

**Pull request merged**
