### PR TITLE
NY: Remove spaces from party names, and disallow null parties

### PR DESCRIPTION
**Pull request by mileswwatkins**

### CODE REVIEW

**Comment by rshorey** [comment]
what happens if party is empty string? does this fail in billy validations?

**Comment by mileswwatkins** [comment]
Double-checking now.

**Comment by paultag** [comment]
blank *should* fail

**Comment by paultag** [comment]
Yeah - https://github.com/sunlightlabs/billy/blob/master/billy/schemas/person.json#L20 - blank isn't set to `True`

**Comment by mileswwatkins** [comment]
Confirmed!
`14:21:37 WARNING billy: Failed to validate field 'roles' list schema: Value '' for field 'party' cannot be blank'`

**Pull request merged**
