### PR TITLE
FL: Add 2016 session, currently with no bills

### PR DESCRIPTION
**Pull request by mileswwatkins**

### CODE REVIEW

**Comment by mileswwatkins** [comment]
Their 2015 Special Session A is definitely finished, though, according to [the calendar PDF](https://www.flsenate.gov/Session/Calendar/2015A).

**Comment by rshorey** [comment]
were we waiting on this for some reason, or should I review/merge?

**Comment by mileswwatkins** [comment]
Review away! Working on my end.

**Comment by mileswwatkins** [comment]
<3 my Florida Bill scrapers.

**Comment by rshorey** [comment]
failing locally for me on session 2015B. Is this a cache issue (just turned it to run without cache) or an actual error?

**Comment by rshorey** [comment]
actually ran again and looked ok, probably a cache issue, running one more time from scratch, then will merge if that sounds right to you, @mileswwatkins

**Comment by rshorey** [comment]
yep, definitely cache. we're good to go.

**Pull request merged**
