### PR TITLE
SD: Switch to 2016 session, per change in the website

### PR DESCRIPTION
**Pull request by mileswwatkins**
@paultag, let's talk about this on Monday.

### CODE REVIEW

**Comment by mileswwatkins** [comment]
(Note to not pull this in until we talk.)

**Comment by mileswwatkins** [comment]
We're just going to turn off SD for now, and turn it back on late this year when bill-prefiles come out.

**Comment by paultag** [comment]
It's worth checking this in perhaps commented out @mileswwatkins

**Comment by paultag** [comment]
:+1:, thanks!

On Tue, May 19, 2015 at 11:10 AM, Miles Watkins <notifications@github.com>
wrote:

> Merged #728 <https://github.com/sunlightlabs/openstates/pull/728>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sunlightlabs/openstates/pull/728#event-308564883>.
>



-- 
Paul Tagliamonte
Software Developer | Sunlight Foundation

**Pull request merged**
